for (const f of ['10_util.js', '13_textures.js', '20_weapons.js', '30_models.js', '32_agents.js', '33_guns.js']) await new Promise((res, rej) => { const s = document.createElement('script'); s.src = '/src/' + f; s.onload = res; s.onerror = rej; document.head.appendChild(s); });
await Agents.load(await (await fetch('/soldier.glb')).arrayBuffer());
if (window.__setup) window.__setup();
const r = new THREE.WebGLRenderer({ antialias: true }); r.setSize(480, 270); r.outputColorSpace = THREE.SRGBColorSpace; r.toneMapping = THREE.ACESFilmicToneMapping;
const scene = new THREE.Scene(); scene.background = new THREE.Color(0xb9a888);
const envS = new THREE.Scene(); envS.add(new THREE.Mesh(new THREE.SphereGeometry(10, 16, 8), new THREE.MeshBasicMaterial({ side: THREE.BackSide, color: 0xc8d4e0 })));
scene.environment = new THREE.PMREMGenerator(r).fromScene(envS).texture; scene.environmentIntensity = .8;
scene.add(new THREE.HemisphereLight(0xdfe8ff, 0x8a7458, 1.5)); const d = new THREE.DirectionalLight(0xfff0d6, 3); d.position.set(-2, 4, 3); scene.add(d);
const cam = new THREE.PerspectiveCamera(64, 480 / 270, .01, 10); scene.add(cam);
const ids = window.__ids || ['ak47', 'm4a1s', 'awp', 'deagle', 'glock', 'elite', 'knife', 'he', 'c4', 'p90', 'famas', 'nova', 'negev', 'mp7', 'zeus'];
const cols = 5, rows = Math.ceil(ids.length / cols);
const cv = document.createElement('canvas'); cv.width = cols * 480; cv.height = rows * 270; cv.style.cssText = 'position:absolute;left:0;top:0'; document.body.appendChild(cv); const g2 = cv.getContext('2d');
ids.forEach((id, k) => {
  const def = W[id], cat = def.cat, b = Agents.vmBase(def);
  const vm = new THREE.Group(); const gun = Models.gun(id, 'default', 'CT'); vm.add(gun); cam.add(vm);
  vm.position.set(b[0], b[1], b[2]); vm.rotation.set(0, b[3], 0);
  const arms = Agents.viewArms('CT'); cam.add(arms.root); cam.updateMatrixWorld(true); vm.updateMatrixWorld(true);
  Agents.poseViewArms(arms, gun, cat);
  r.render(scene, cam); g2.drawImage(r.domElement, (k % cols) * 480, Math.floor(k / cols) * 270);
  g2.fillStyle = '#000'; g2.font = '14px sans-serif'; g2.fillText(id, (k % cols) * 480 + 6, Math.floor(k / cols) * 270 + 16);
  cam.remove(vm); cam.remove(arms.root);
});
await snap('grid');
return 'ok';
